### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by saman6barware** [girliemac/send-sms#1]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/username/Desktop/send-sms/server/config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Shooteger** [comment]
I refer to the README file of the project, you need to create your own config.js File:

> Create config.js in /server. The file should include the credentials.
> 
> module.exports = {
>   api_key: 'f321a...',
>   api_secret: '18e9aad...',
>   number: '14155551234'
> };

closes: #1
